-- MySQL Script generated by MySQL Workbench
-- Sun Apr  2 15:16:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Porcinos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Porcinos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Porcinos` DEFAULT CHARACTER SET utf8 ;
USE `Porcinos` ;

-- -----------------------------------------------------
-- Table `Porcinos`.`notificación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`notificación` (
  `id_notificación` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NOT NULL,
  `notificación` LONGTEXT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_notificación`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`reporte_porcino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`reporte_porcino` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `porcino` LONGTEXT NOT NULL,
  `descripción` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_reporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `cedula` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `porcino` VARCHAR(45) NOT NULL,
  `maternidad` VARCHAR(45) NOT NULL,
  `recria` VARCHAR(45) NOT NULL,
  `engorde` VARCHAR(45) NULL,
  `alimento` VARCHAR(45) NOT NULL,
  `medicina` VARCHAR(45) NOT NULL,
  `herramienta` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_rol_usuario_idx` (`id_rol` ASC),
  CONSTRAINT `fk_rol_usuario`
    FOREIGN KEY (`id_rol`)
    REFERENCES `Porcinos`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`tipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `género` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`raza` (
  `id_raza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_raza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`recria_descripción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`recria_descripción` (
  `id_recria_d` INT NOT NULL AUTO_INCREMENT,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_destete` DATE NOT NULL,
  ` peso` DOUBLE NULL,
  `grupo` INT NULL,
  `numero_cerdos` INT NULL,
  `corral` INT NULL,
  `arete_macho` VARCHAR(45) NOT NULL,
  `machos` INT NULL,
  `arete_hembra` VARCHAR(45) NOT NULL,
  `hembras` INT NULL,
  `edad_salida` INT NULL,
  `peso_salida` DOUBLE NULL,
  `consumo_alimento` INT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_recria_d`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`porcino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`porcino` (
  `id_porcino` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `id_tipo` INT NOT NULL,
  `id_raza` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  ` fecha_nacimiento` DATE NULL,
  `fecha_adquisiscion` DATE NULL,
  `observacion` VARCHAR(100) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_porcino`),
  INDEX `fk_raza_porcino_idx` (`id_raza` ASC),
  INDEX `fk_tipo_porcino_idx` (`id_tipo` ASC),
  CONSTRAINT `fk_raza_porcino`
    FOREIGN KEY (`id_raza`)
    REFERENCES `Porcinos`.`raza` (`id_raza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_porcino`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `Porcinos`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`tratamientolechones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`tratamientolechones` (
  `id_tratamiento` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `numero_parto` INT NOT NULL,
  `tratamiento` VARCHAR(45) NOT NULL,
  `descripcion` DOUBLE NOT NULL,
  ` fecha_tratamiento` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tratamiento`),
  INDEX `fk_porcino_tratamientolechones_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_porcino_tratamientolechones`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`medicamento` (
  `id_medicamento` INT NOT NULL AUTO_INCREMENT,
  `nombre_medicamento` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `stock` DOUBLE NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_medicamento`),
  CONSTRAINT `fk_tratamientolechones_medicamento`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `Porcinos`.`tratamientolechones` (`id_tratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`recria_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`recria_diario` (
  `id_recriadiario` INT NOT NULL AUTO_INCREMENT,
  `id_recria_d` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `edad_cerdos` INT NOT NULL,
  `numero_cerdos` INT NOT NULL,
  `consumo` INT NOT NULL,
  `id_medicamento` INT NOT NULL,
  `mortalidad` VARCHAR(45) NOT NULL,
  `alimentacion` VARCHAR(45) NOT NULL,
  `salen` INT NULL,
  `corral` INT NULL,
  `codigo_cerdo` VARCHAR(45) NULL,
  `dosis` DOUBLE NOT NULL,
  `observacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_recriadiario`),
  INDEX `fk_recria_descripcion_recria_diario_idx` (`id_recria_d` ASC),
  INDEX `fk_medicamento_recria_diario_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_recria_descripción_recria_diario`
    FOREIGN KEY (`id_recria_d`)
    REFERENCES `Porcinos`.`recria_descripción` (`id_recria_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_recria_diario`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `Porcinos`.`medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`reporte_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`reporte_usuario` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_reporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`remplazo_chanchillas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`remplazo_chanchillas` (
  `id_remplazo` INT NOT NULL AUTO_INCREMENT,
  `no_camada` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `no_padre` INT NOT NULL,
  `no_madre` INT NOT NULL,
  `fecha_vacuna` DATE NOT NULL,
  `id_vacuna` INT NOT NULL,
  `semana_monta` VARCHAR(45) NULL,
  `deteccion_celo` VARCHAR(45) NOT NULL,
  `observacion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_remplazo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`herramientas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`herramientas` (
  `id_herramientas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado_herramienta` VARCHAR(45) NOT NULL,
  `Cantidad` INT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_herramientas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`recria_porcino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`recria_porcino` (
  `id_recria_p` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `id_raza` INT NOT NULL,
  `id_recria_d` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_recria_p`),
  INDEX `fk_raza_recria_porcino_idx` (`id_raza` ASC),
  INDEX `fk_recria_descripcion_recria_porcino_idx` (`id_recria_d` ASC),
  INDEX `fk_porcino_recria_porcino_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_raza_recria_porcino`
    FOREIGN KEY (`id_raza`)
    REFERENCES `Porcinos`.`raza` (`id_raza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recria_descripción_recria_porcino`
    FOREIGN KEY (`id_recria_d`)
    REFERENCES `Porcinos`.`recria_descripción` (`id_recria_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_porcino_recria_porcino`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`alimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`alimentos` (
  `id_alimentos` INT NOT NULL AUTO_INCREMENT,
  `nombre_alimento` VARCHAR(45) NOT NULL,
  `cantidad` DOUBLE NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_alimentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`maternidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`maternidad` (
  `id_maternidad` INT NOT NULL AUTO_INCREMENT,
  `fecah_parto_real` DATE NOT NULL,
  `fecha_ingreso_maternidad` DATE NOT NULL,
  ` id_porcino` INT NOT NULL,
  `numero_parto` INT NOT NULL,
  `numero_hijos_total` INT NOT NULL,
  `numero_hijo_vivos` INT NOT NULL,
  `numero_hijos_debiles` INT NOT NULL,
  `numero_hijos_muertos` INT NOT NULL,
  `numero_hijos_momificados` INT NOT NULL,
  `hijos_destetados` INT NOT NULL,
  `fecha_destete_actual` DATE NOT NULL,
  `observacion` VARCHAR(45) NULL,
  `consumo_madre` DOUBLE NOT NULL,
  `consume_lechones` DOUBLE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_maternidad`),
  INDEX `fk_porcino_maternidad_idx` (` id_porcino` ASC),
  CONSTRAINT `fk_porcino_maternidad`
    FOREIGN KEY (` id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`lechonesmuertos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`lechonesmuertos` (
  `id_muertos` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `numero_parto` INT NOT NULL,
  `fecha_muertos` DATETIME NOT NULL,
  `numero_muertos` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_muertos`),
  INDEX `fk_porcino_lechonesmuertos_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_porcino_lechonesmuertos`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`traspaso_lechones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`traspaso_lechones` (
  `id_traspaso` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `numero_parto` INT NOT NULL,
  `fecha_traspaso` DATETIME NOT NULL,
  `traspaso_hembra` VARCHAR(45) NOT NULL,
  `numero_lechones` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_traspaso`),
  INDEX `fk_porcino_traspaso_lechones_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_porcino_traspaso_lechones`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`corral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`corral` (
  `id_corral` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL,
  `corral` INT NOT NULL,
  `id_porcino` INT NOT NULL,
  `id_porcino_engorde` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_corral`),
  INDEX `fk_porcino_corral_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_porcino_corral`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`gestacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`gestacion` (
  `id_gestacion` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `numero_parto` INT NOT NULL,
  `fecha_destete_anterior` DATE NULL,
  `cod_macho` VARCHAR(45) NOT NULL,
  `fecha_monta` DATE NOT NULL,
  `parto_probable` DATE NOT NULL,
  `nacido_vivo_parto_anterior` INT NULL,
  `color` DATE NOT NULL,
  `tex` DATE NOT NULL,
  `ojo` DATE NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_gestacion`),
  INDEX `fk_porcino_gestacion_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_porcino_gestacion`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`tratamientohembras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`tratamientohembras` (
  `id_tratamiento` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `numero_parto` INT NOT NULL,
  `tratamiento` VARCHAR(45) NOT NULL,
  `descripcion` DOUBLE NULL,
  `fecha_tratamiento` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tratamiento`),
  INDEX `fk_porcino_tratamiento_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_porcino_tratamiento`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`acepta_lechones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`acepta_lechones` (
  `id_acepta` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `numero_parto` INT NULL,
  `fecha_acepta` DATETIME NOT NULL,
  `acepta_hembra` VARCHAR(45) NOT NULL,
  `numero_lechones` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_acepta`),
  INDEX `fk_porcino_acepta_lechones_idx` (`id_porcino` ASC),
  CONSTRAINT `fk_porcino_acepta_lechones`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`engorde_descripción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`engorde_descripción` (
  `id_engorde_d` INT NOT NULL AUTO_INCREMENT,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_sal_rec` DATE NOT NULL,
  `peso_recria` DOUBLE NOT NULL,
  `grupo` INT NULL,
  `numero_cerdos` INT NOT NULL,
  `edad_salida_rec` INT NOT NULL,
  `corral` INT NOT NULL,
  `arete_macho` VARCHAR(45) NOT NULL,
  `machos` INT NOT NULL,
  `arete_hembra` VARCHAR(45) NOT NULL,
  `hembras` INT NOT NULL,
  `edad_salida` INT NOT NULL,
  `peso_salida` DOUBLE NOT NULL,
  `grupo_conversion` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_engorde_d`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`engorde_porcino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`engorde_porcino` (
  `id_engorde_p` INT NOT NULL AUTO_INCREMENT,
  `id_porcino` INT NOT NULL,
  `id_raza` INT NOT NULL,
  `id_engorde_d` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_engorde_p`),
  INDEX `fk_porcino_engorde_porcino_idx` (`id_porcino` ASC),
  INDEX `fk_raza_engorde_porcino_idx` (`id_raza` ASC),
  CONSTRAINT `fk_porcino_engorde_porcino`
    FOREIGN KEY (`id_porcino`)
    REFERENCES `Porcinos`.`porcino` (`id_porcino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_raza_engorde_porcino`
    FOREIGN KEY (`id_raza`)
    REFERENCES `Porcinos`.`raza` (`id_raza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_engorde_descripción_engorde_porcino`
    FOREIGN KEY (`id_engorde_p`)
    REFERENCES `Porcinos`.`engorde_descripción` (`id_engorde_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`engorde_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`engorde_diario` (
  `id_engordediario` INT NOT NULL AUTO_INCREMENT,
  `id_engorde_d` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `edad_cerdos` INT NOT NULL,
  `numero_cerdos` INT NULL,
  `consumo` INT NOT NULL,
  `id_medicamento` INT NOT NULL,
  `mortalidad` VARCHAR(45) NULL,
  `alimentacion` VARCHAR(45) NOT NULL,
  `salen` INT NOT NULL,
  `corral` INT NOT NULL,
  `codigo_cerdo` VARCHAR(45) NOT NULL,
  `dosis` DOUBLE NOT NULL,
  ` observaciones` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_engordediario`),
  INDEX `fk_engorde_descripción_engorde_diario_idx` (`id_engorde_d` ASC),
  INDEX `fk_medicamento_engorde_diario_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_engorde_descripción_engorde_diario`
    FOREIGN KEY (`id_engorde_d`)
    REFERENCES `Porcinos`.`engorde_descripción` (`id_engorde_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_engorde_diario`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `Porcinos`.`medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Porcinos`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porcinos`.`tarea` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `id_notificación` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_notificación_tarea_idx` (`id_notificación` ASC),
  CONSTRAINT `fk_notificación_tarea`
    FOREIGN KEY (`id_notificación`)
    REFERENCES `Porcinos`.`notificación` (`id_notificación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
